GROUP_RE_PATTERN: 
    .+org.chromium.chrome.browser(\.\w+\.)

HEADER: >
    digraph "G" {
        fontsize=96;
        graph [rankdir=LR,
               label="Chromium",
               labelloc=top];
    node [fontname=Helvetica,
        fontsize=8,
        label="",
        shape=record,
    ];
    edge [fontname=Helvetica,
        fontsize=8,
        labelfontname=Helvetica,
        labelfontsize=8
    ];

FOOTER: >
    }


FILTERED_FIELDS: [URL]

FILTERED_RE_NODES: []

FILTERED_EXACT_NODES: [String, int, File, Boolean, boolean, Date,
                        long, Object, short, double, byte, float]

PROBLEM_NODES: [swing, JLabel, JScrollPane, JDialog, JPanel,
                 Dialog, Graphic, graphic, Renderer, JComponent,
                 Cursor, JFrame]

PACKAGE_COLORS: 
    .infobar.: blue1
    .banners.: blueviolet
    .widget.: coral3
    .dom_distiller.: darkolivegreen
    .accessibility.: dodgerblue4
    .signin.: gold
    .sync.: azure3
    .appmenu: aquamarine3
    problem: red
    other: white

