GROUP_RE_PATTERN: 
    .com.cardiscope(\.\w+\.)

HEADER: >
    digraph "G" {
        fontsize=96;
        graph [rankdir=LR,
               label="Chromium",
               labelloc=top];
    node [fontname=Helvetica,
        fontsize=8,
        label="",
        shape=record,
    ];
    edge [fontname=Helvetica,
        fontsize=8,
        labelfontname=Helvetica,
        labelfontsize=8
    ];

FOOTER: >
    }


FILTERED_FIELDS: [URL]

FILTERED_RE_NODES: [.view, tukaani, SidePanel, help, theme, ArrayList, ActionListener, JListi,
                    Hashtable, Vector, ArrayList, HashMap, HashSet, TreeMap, Constructori,
                    Map\< String, Comparable, JSONObject]

FILTERED_EXACT_NODES: [String, int, File, RandomAccessFile, Boolean, boolean, Date,
                        long, Object, short, double, byte, float, CommConnection,
                        JPopupMenu, BufferedImage, Color, Timer, CommListener, Paint, Dimension,
                        DataOutputStream, JFrame, JTextField, Border, FilesSystemView,
                        Socket, OutputStream, Runnable, Cloneable, DataInput, Closeable,
                        JTable, InputStream, Cursor, SimpleDateFormat, JPanel, JButton,
                        JFrame, JPaneEx, JPopupMenu, FileSystemView, JComponent,
                        ComponentListener, dblClickListener, ActionListener, MouseListener,
                        Border, HashMap\< Integer, JSONObject \>, HashSet\< Integer \>, 
                        ArrayList\< Object \>, Hashtable\< String,\l Double \>,
                        Comparable\< Double \>, ArrayList\< Double \>, Hashtable\< String,\l Boolean \>,
                        Hashtable\< String,\l Double \>, HashMap\< Integer, JSONObject \>,
                        Map\< String, HttpAsyncRequest\lHandler\< HttpRequest \> \>, ExecutorService,
                        com.cardiscope.notification]

PROBLEM_NODES: [swing, JLabel, JScrollPane, JDialog, JPanel,
                 Graphic, graphic, Renderer, JComponent,
                 Cursor, JFrame]

PACKAGE_COLORS: 
    .bdac.: blue1
    .data.: blueviolet
    .db.: coral3
    .narrative.: darkolivegreen
    .processor.: dodgerblue4
    .utils.: gold
    .crypt.: azure3
    .JSON: aquamarine3
    .view.: pink
    .webapi.: yellow
    problem: red
    other: white

