GROUP_RE_PATTERN: 
    .com.cardiscope(\.\w+\.)

HEADER: >
    digraph "G" {
        fontsize=96;
        graph [rankdir=LR,
               label="Chromium",
               labelloc=top];
    node [fontname=Helvetica,
        fontsize=8,
        label="",
        shape=record,
    ];
    edge [fontname=Helvetica,
        fontsize=8,
        labelfontname=Helvetica,
        labelfontsize=8
    ];

FOOTER: >
    }


FILTERED_FIELDS: [URL]

FILTERED_RE_NODES: [.view, tukaani, SidePanel, help, theme]

FILTERED_EXACT_NODES: [String, int, File, RandomAccessFile, Boolean, boolean, Date,
                        long, Object, short, double, byte, float,
                        JPopupMenu, BufferedImage, Color, Timer,
                        DataOutputStream, JFrame, JTextField, Border, FilesSystemView,
                        Socket, OutputStream, Runnable, Cloneable, DataInput, Closeable,
                        JTable, InputStream, Cursor, SimpleDateFormat, JPanel, JButton,
                        JFrame, JPaneEx, JPopupMenu, FileSystemView,
                        ComponentListener, dblClickListener, ActionListener, MouseListener,
                        Border]

PROBLEM_NODES: [swing, JLabel, JScrollPane, JDialog, JPanel,
                 Graphic, graphic, Renderer, JComponent,
                 Cursor, JFrame]

PACKAGE_COLORS: 
    .bdac.: blue1
    .data.: blueviolet
    .db.: coral3
    .narrative.: darkolivegreen
    .processor.: dodgerblue4
    .utils.: gold
    .crypt.: azure3
    .JSON: aquamarine3
    .view.: pink
    .webapi.: yellow
    problem: red
    other: white

