GROUP_RE_PATTERN: 
    .com.cardiscope(\.\w+\.)

HEADER: >
    digraph "G" {
        fontsize=96;
        graph [rankdir=LR,
               label="$HEADER$",
               labelloc=top];
    node [fontname=Helvetica,
        fontsize=10,
        label="",
        shape=record,
    ];
    edge [fontname=Helvetica,
        fontsize=10,
        labelfontname=Helvetica,
        labelfontsize=10
    ];

FOOTER: >
    }


FILTERED_FIELDS: [URL]

FILTERED_RE_NODES: [.view, tukaani, SidePanel, help, theme, ArrayList, Listener,
                    Hashtable, Vector, ArrayList, 
                    HashSet, Constructor, Stack,
                    Comparable, JSONObject, IOException, '.*\.sevenzip\..*', Test,
                    ListCellRenderer, ByReference, Notification, '.*Server\.log.*',
                    '.*Map\\<.+',
                    '.*J[a-zA-Z]+.+']

FILTERED_EXACT_NODES: [ # Basic types 
                        String, int, File, long, Object, short, double, byte, float,Boolean, boolean, Date,
                        # UI elements
                        #JPopupMenu, JFrame, JTextField, JTable, JScrollPane, JSplitPane, JLabel, JPanel, 
                        #JFrame, JPaneEx, JPopupMenu, JComponent, JDialog, JProgressBar, JDateChooser, JDesktopPane,
                        #JFormattedTextField, JDialog, JButton, JWindow, JToggleButton, JPasswordField, JTextArea,
                        #JToggleButton, JCheckBox,
                        Color, Timer, Paint, Font, DragSource, TexturePaint, Composite, CompositeContext,
                        Border, Clip, BasicStroke, ListSelectionModel, FileSystemView, FilesSystemView,
                        DefaultListModel, LayoutManager2, Graphics2D, DefaultListCellRenderer, DefaultTableCellRenderer,
                        # Listeners
                        #CommListener, ComponentListener, dblClickListener, ActionListener, MouseListener, DiscoveryListener,
                        #LineListener, WindowListener, EventListener, MouseMotionListener, ListSelectionListener,
                        # Adapters
                        MouseAdapter,
                        # Streams and files
                        OutputStream, DataOutputStream, DataInput, InputStream, DataInputStream,RandomAccessFile, 
                        ReadableByteChannel, PipedOutputStream, BufferedOutputStream, FileOutputStream, MappedByteBuffer,
                        BufferedImage, BufferedInputStream, ZipOutputStream, ByteBuffer, DataOutput, PipedInputStream,
                        # Database
                        AbstractTableModel, PreparedStatement, Cursor, 
                        # Others
                        CommConnection, Connection, SSLServerSocket, ThreadFactory, Thread,
                        Dimension, TimerTask,
                        Socket, Runnable, Cloneable, Closeable, Transferable,
                        SimpleDateFormat, Window, Point, 
                        HttpAsyncRequest\lHandler\< HttpRequest \> \>, ExecutorService,
                        com.cardiscope.notification, err, 
                        Printable, PrintStream, ClipboardOwner, Colour, CRC32, Image, ImageTranscoder, TranscoderInput,
                        UUID, Locale, Charset, Properties, SVGDocument,
                        WString, Pointer, Structure, RuntimeException, CountDownLatch
                        ]

FILTER_IGNORE: [ # Example: '.*MouseAdapter.*' 
                ]

PROBLEM_NODES: [swing, Graphic, graphic, Cursor]

PACKAGE_COLORS: 
    .bdac.: blue1
    .data.: blueviolet
    .db.: coral3
    .narrative.: darkolivegreen
    .processor.: dodgerblue4
    .utils.: gold
    .crypt.: azure3
    .license.: aquamarine3
    .report.: pink
    .webapi.: yellow
    problem: red
    other: white

